added http status code 419
Roobarb/hkjl-bot pull request #20
Opened 2017-06-08 19:15 UTC by trirpi

2017-06-09 07:24 UTC, casdr approved these changes

2017-06-09 09:19 UTC, casdr requested changes

2017-06-09 09:19 UTC, casdr commented on bot.php
> +        if(($message=="ok"||$message=="oke") && rand(1,4)==2) output("is goed");
This shouldn't be in this PR

2017-06-09 18:50 UTC, trirpi commented on bot.php
> +        if(($message=="ok"||$message=="oke") && rand(1,4)==2) output("is goed");
I thought that was another PR. But now it is in the same one.

2017-06-12 17:14 UTC, trirpi commented on bot.php
> +        if(($message=="ok"||$message=="oke") && rand(1,4)==2) output("is goed");
ja dan zal k dat doen zkers

2017-06-12 17:14 UTC, trirpi commented on bot.php
> +        if(($message=="ok"||$message=="oke") && rand(1,4)==2) output("is goed");
ff kijken hoe

2017-06-12 17:25 UTC, casdr commented
Closed in favor of #21

2017-06-12 17:25 UTC, closed without merging